version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: infra/docker/backend.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB_PATH=/app/apps/backend/data/database.sqlite
      - CAMARA_API_BASE_URL=https://dadosabertos.camara.leg.br/api/v2

  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
    ports:
      - '4200:4200'
    environment:
      - API_BASE_URL=http://backend:3000/api
    depends_on:
      - backend
